/**
 * SITE ANALYZER PRO v4.0.0 (Tuning Update)
 * Транспорт: Direct -> Worker -> Proxy (Fallback system)
 */

// --- ТРАНСПОРТНЫЙ СЛОЙ (Возврат логики v3.4) ---
async function fetchPage(url) {
    const worker = document.getElementById('workerUrl').value;
    const proxyList = [
        { n: 'Direct', u: url, direct: true },
        { n: 'Worker', u: `${worker}/?url=${encodeURIComponent(url)}`, direct: false },
        { n: 'AllOrigins', u: `https://api.allorigins.win/raw?url=${encodeURIComponent(url)}`, direct: false },
        { n: 'CorsProxy', u: `https://corsproxy.io/?${encodeURIComponent(url)}`, direct: false }
    ];

    for (const p of proxyList) {
        try {
            console.log(`[Transport] Попытка: ${p.n}`);
            const resp = await fetch(p.u);
            if (!resp.ok) throw new Error('HTTP ' + resp.status);
            
            const html = await resp.text();
            if (html.length < 500) throw new Error('Empty/Small response');
            
            // Если успех, запоминаем домен для whitelist (если это не прокси)
            if (p.direct) state.whitelist.add(new URL(url).hostname);
            
            return html;
        } catch (e) {
            console.warn(`[Transport] ${p.n} не прошел: ${e.message}`);
        }
    }
    throw new Error('Все методы доступа (Direct/Worker/Proxy) заблокированы.');
}

// --- УЛУЧШЕННЫЙ SMART EXTRACTOR ---
async function analyzeVideoSources(doc, html) {
    const sources = [];
    const q = {};

    // 1. KVS / Variable extraction (Улучшенные регулярки)
    const vars = ['video_url', 'video_alt_url', 'file', 'video_hls'];
    vars.forEach(v => {
        const re = new RegExp(`${v}:\\s*['"]([^'"]+)['"]`, 'g');
        let m;
        while ((m = re.exec(html)) !== null) {
            sources.push({ url: m[1].replace(/\\/g, ''), type: 'kvs_var', quality: v });
        }
    });

    // 2. HTML5 Source
    doc.querySelectorAll('source[src]').forEach(s => {
        sources.push({ url: s.src, type: 'source_tag', quality: s.getAttribute('size') || 'SD' });
    });

    // 3. Health check & Whitelist
    for (let s of sources) {
        try { 
            state.whitelist.add(new URL(s.url).hostname); 
            s.health = await checkLinkHealth(s.url);
        } catch(e) {}
    }

    return sources;
}

// --- ГЕНЕРАТОР ПАРСЕРА (Умный перебор) ---
function generateParserTemplate(analysis) {
    const host = state.targetHost;
    
    return `// Parser for ${host}
// Generated by Site Analyzer Pro v4.0.0

qualities: function(videoPageUrl, success, error) {
    // Используем стандартную функцию получения данных
    httpGet(videoPageUrl, function(html) {
        const q = {};
        
        // 1. Поиск KVS переменных
        const vars = ['video_url', 'video_alt_url', 'video_hls'];
        vars.forEach(v => {
            const m = html.match(new RegExp(v + ":\\s*['" + '"]([^' + "'" + '"]+)' + "['" + '"]'));
            if (m) q[v] = m[1].replace(/\\\\/g, '');
        });

        // 2. Поиск через Regex (альтернатива)
        const mp4 = html.match(/https?:\\/\\/[^"']+\\.mp4/);
        if (mp4) q['MP4'] = mp4[0];

        if (Object.keys(q).length > 0) success({ qualities: q });
        else error('Video not found');
    }, error);
}`;
}
